ALTER TABLE users
    ADD COLUMN is_protected TINYINT(1) NOT NULL DEFAULT 0 AFTER is_setup;

ALTER TABLE resource_groups
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
