CREATE TABLE IF NOT EXISTS ticket_execution_rollbacks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ticket_id BIGINT UNSIGNED NOT NULL,
  execution_id BIGINT UNSIGNED NOT NULL,
  seq INT NOT NULL,
  status VARCHAR(32) NOT NULL,
  unsupported_reason TEXT NULL,
  failure_message TEXT NULL,
  generator VARCHAR(64) NOT NULL DEFAULT '',
  generator_version VARCHAR(128) NOT NULL DEFAULT '',
  source_connection_id BIGINT UNSIGNED NOT NULL,
  source_database_name VARCHAR(255) NULL,
  source_schema_name VARCHAR(255) NULL,
  binlog_start_file VARCHAR(255) NULL,
  binlog_start_pos BIGINT UNSIGNED NULL,
  binlog_end_file VARCHAR(255) NULL,
  binlog_end_pos BIGINT UNSIGNED NULL,
  rollback_sql_encrypted LONGBLOB NULL,
  rollback_sql_sha256 CHAR(64) NULL,
  rollback_sql_bytes BIGINT NULL,
  statement_count INT NULL,
  confidence VARCHAR(32) NULL,
  warning_message TEXT NULL,
  rollback_ticket_id BIGINT UNSIGNED NULL,
  generated_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uk_ticket_execution_rollbacks_execution (execution_id),
  KEY idx_ticket_execution_rollbacks_ticket (ticket_id),
  KEY idx_ticket_execution_rollbacks_status (status),
  CONSTRAINT fk_ticket_execution_rollbacks_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_ticket_execution_rollbacks_execution FOREIGN KEY (execution_id) REFERENCES ticket_executions(id) ON DELETE CASCADE,
  CONSTRAINT fk_ticket_execution_rollbacks_connection FOREIGN KEY (source_connection_id) REFERENCES db_connections(id),
  CONSTRAINT fk_ticket_execution_rollbacks_rollback_ticket FOREIGN KEY (rollback_ticket_id) REFERENCES tickets(id)
);
