CREATE TABLE IF NOT EXISTS db_session_loop_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    requested_by BIGINT UNSIGNED NOT NULL,
    connection_id BIGINT UNSIGNED NOT NULL,
    engine VARCHAR(16) NOT NULL,
    target_mode VARCHAR(16) NOT NULL,
    region VARCHAR(64) NOT NULL DEFAULT '',
    cluster_id VARCHAR(255) NOT NULL DEFAULT '',
    node_id VARCHAR(255) NOT NULL DEFAULT '',
    target_host VARCHAR(255) NOT NULL DEFAULT '',
    target_port INT UNSIGNED NOT NULL DEFAULT 0,
    target_key CHAR(64) NOT NULL,
    active_target_key CHAR(64) NULL,
    database_name VARCHAR(255) NOT NULL,
    prefix_encrypted BLOB NULL,
    prefix_shape TEXT NOT NULL,
    prefix_hash CHAR(64) NOT NULL,
    minimum_age_seconds INT UNSIGNED NOT NULL,
    interval_seconds INT UNSIGNED NOT NULL,
    duration_seconds INT UNSIGNED NOT NULL,
    max_kills INT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    kill_count INT UNSIGNED NOT NULL DEFAULT 0,
    consecutive_errors INT UNSIGNED NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64) NULL,
    last_error_message VARCHAR(255) NULL,
    started_at DATETIME(6) NULL,
    expires_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_db_session_loop_jobs_active_target (active_target_key),
    KEY idx_db_session_loop_jobs_status_created (status, created_at),
    KEY idx_db_session_loop_jobs_connection_created (connection_id, created_at),
    CONSTRAINT fk_db_session_loop_jobs_requester FOREIGN KEY (requested_by) REFERENCES users(id),
    CONSTRAINT fk_db_session_loop_jobs_connection FOREIGN KEY (connection_id) REFERENCES db_connections(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
