CREATE TABLE table_schema_sync_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    requested_by BIGINT UNSIGNED NOT NULL,
    source_connection_id BIGINT UNSIGNED NOT NULL,
    source_database VARCHAR(64) NOT NULL,
    target_connection_id BIGINT UNSIGNED NOT NULL,
    target_database VARCHAR(64) NOT NULL,
    transformation_config JSON NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'queued',
    active_target_key VARCHAR(160) NULL,
    cancel_requested_by BIGINT UNSIGNED NULL,
    retry_of_job_id BIGINT UNSIGNED NULL,
    table_count INT UNSIGNED NOT NULL,
    created_count INT UNSIGNED NOT NULL DEFAULT 0,
    failed_count INT UNSIGNED NOT NULL DEFAULT 0,
    not_started_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(255) NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_table_schema_sync_active_target (active_target_key),
    KEY idx_table_schema_sync_status_created (status, created_at, id),
    KEY idx_table_schema_sync_source (source_connection_id, created_at),
    KEY idx_table_schema_sync_target (target_connection_id, created_at),
    CONSTRAINT fk_table_schema_sync_requester FOREIGN KEY (requested_by) REFERENCES users(id),
    CONSTRAINT fk_table_schema_sync_source FOREIGN KEY (source_connection_id) REFERENCES db_connections(id),
    CONSTRAINT fk_table_schema_sync_target FOREIGN KEY (target_connection_id) REFERENCES db_connections(id),
    CONSTRAINT fk_table_schema_sync_retry FOREIGN KEY (retry_of_job_id) REFERENCES table_schema_sync_jobs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE table_schema_sync_job_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id BIGINT UNSIGNED NOT NULL,
    table_name VARCHAR(64) NOT NULL,
    dependency_order INT UNSIGNED NOT NULL,
    source_ddl_sha256 CHAR(64) NOT NULL,
    target_ddl_sha256 CHAR(64) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    error_code VARCHAR(64) NULL,
    duration_ms BIGINT UNSIGNED NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_table_schema_sync_item (job_id, table_name),
    UNIQUE KEY uk_table_schema_sync_order (job_id, dependency_order),
    CONSTRAINT fk_table_schema_sync_item_job FOREIGN KEY (job_id) REFERENCES table_schema_sync_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
