CREATE TABLE ticket_online_ddl_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ticket_id BIGINT UNSIGNED NOT NULL,
    execution_id BIGINT UNSIGNED NOT NULL,
    connection_id BIGINT UNSIGNED NOT NULL,
    executor_id BIGINT UNSIGNED NOT NULL,
    mode VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    phase VARCHAR(32) NULL,
    initial_parameters JSON NOT NULL,
    effective_parameters JSON NOT NULL,
    sql_sha256 CHAR(64) NOT NULL,
    preflight_sha256 CHAR(64) NOT NULL,
    tool_version VARCHAR(64) NULL,
    progress_percent DECIMAL(5,2) NULL,
    copied_rows BIGINT UNSIGNED NULL,
    eta_seconds BIGINT UNSIGNED NULL,
    replication_lag_ms BIGINT UNSIGNED NULL,
    threads_running INT UNSIGNED NULL,
    throttle_reason VARCHAR(255) NULL,
    heartbeat_at DATETIME(6) NULL,
    pause_requested TINYINT(1) NOT NULL DEFAULT 0,
    cancel_requested TINYINT(1) NOT NULL DEFAULT 0,
    outcome_confidence VARCHAR(32) NULL,
    artifact_summary JSON NULL,
    error_code VARCHAR(64) NULL,
    active_connection_id BIGINT UNSIGNED NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_online_ddl_execution (execution_id),
    UNIQUE KEY uk_online_ddl_active_connection (active_connection_id),
    KEY idx_online_ddl_ticket (ticket_id, execution_id),
    KEY idx_online_ddl_status_created (status, created_at, id),
    CONSTRAINT fk_online_ddl_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
    CONSTRAINT fk_online_ddl_execution FOREIGN KEY (execution_id) REFERENCES ticket_executions(id) ON DELETE CASCADE,
    CONSTRAINT fk_online_ddl_connection FOREIGN KEY (connection_id) REFERENCES db_connections(id),
    CONSTRAINT fk_online_ddl_executor FOREIGN KEY (executor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_online_ddl_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id BIGINT UNSIGNED NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    event_type VARCHAR(32) NOT NULL,
    phase VARCHAR(32) NULL,
    progress_percent DECIMAL(5,2) NULL,
    before_parameters JSON NULL,
    after_parameters JSON NULL,
    result VARCHAR(32) NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_online_ddl_event_run_created (run_id, created_at, id),
    CONSTRAINT fk_online_ddl_event_run FOREIGN KEY (run_id) REFERENCES ticket_online_ddl_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_online_ddl_event_actor FOREIGN KEY (actor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
